Cast the results of x.find_all() to a list for Python 3
x.find_all() will return a __list__ in Python 2 and an __iterator__ in Python 3.  Force the result into a list for __bool()__, __len()__, and indexing.
```
ERROR: Test creating an ask and sending it to others
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Test/Community/Market/test_community.py", line 76, in test_create_ask
    self.assertTrue(orders[0].verified)
TypeError: 'dict_values' object does not support indexing
```