str are already Unicode utf-8 by default in Python 3 (#4318)
* str are already Unicode utf-8 by default in Python 3

```
ERROR: test_get_index
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Test/test_as_server.py", line 62, in check
    result = fun(*argv, **kwargs)
  File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Test/Core/test_torrent_def.py", line 445, in test_get_index
    self.assertEqual(t.get_index_of_file_in_files('a.txt'), 0)
  File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Core/TorrentDef.py", line 790, in get_index_of_file_in_files
    intorrentpath = maketorrent.pathlist2filename(file_dict['path'])
  File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Core/Utilities/maketorrent.py", line 258, in pathlist2filename
    return fullpath.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

* Remove trailing whitespace

* fullpath = os.path.join(*pathlist)

* Use codecs.decode() and catch TypeError instead of AttributeError

* Use codecs.decode() and catch TypeError instead of AttributeError